version: "3.6"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - default
    volumes:
      - ./redis:/redis
  
  postgresdb:
    environment:
      - POSTGRES_PASSWORD=Passw0rd9
    image: postgres:latest
    networks:
      - default
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgresdb
    image: flask-app-api
    networks:
      - default
    ports:
      - 5005:5000
    volumes:
      - .:/app
    working_dir: /app
    restart: always

  worker:
    image: flask-app-api
    networks:
      - default
    depends_on:
      - redis
    command: rq worker --url redis://redis:6379 emails
    links:
      - redis