"""empty message

Revision ID: 522d0d16c356
Revises: c2ad737ae3a1
Create Date: 2023-03-28 22:50:45.545245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522d0d16c356'
down_revision = 'c2ad737ae3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint('email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
